name: Scrape kuuderes from MAL club

on:
  workflow_dispatch:
  
jobs:
  scrape-anilist:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3
        
      - name: install python packages
        run: |
          pip install jellyfish
      
      - name: execute python script
        run: |
          python -u .github/scripts/scrape_mal.py # -u so we can view console output in realtime
          
      - name: push anilist ids
        run: |
          git add anilist
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -m "Update kuudere AniList IDs from MAL club"
          git push
