name: Scrape kuuderes from MAL club

on:
  workflow_dispatch:
  
  schedule:
    - cron: "38 3 */7 * *" # randomly selected so that the task doesn't get queued during peak periods
  
jobs:
  scrape-anilist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v3
        
      - name: Install Python packages
        run: |
          pip install jellyfish
      
      - name: Execute Python script
        run: |
          python -u .github/scripts/scrape_mal.py # -u so we can view console output in realtime
          
      - name: Push AniList IDs
        run: |
          git add data/anilist.json
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -m "Update kuudere AniList IDs from MAL club"
          git push
